# Add in your keys and tokens.
ACCESS_TOKEN =        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ACCESS_TOKEN_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CONSUMER_KEY =        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CONSUMER_KEY_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

def getKeys():
    return (ACCESS_TOKEN, ACCESS_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_KEY_SECRET)
